name: Sync settings

on:
  push:
    branches:
      - 'main'

jobs:
  upload_settings:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Process and Upload Settings
        id: process_and_upload
        env:
          AUTHORIZATION: ${{ secrets.AUTHORIZATION }} # Use GitHub secret
          REPO_URL: ${{ github.repository }}
          COMMIT_HASH: ${{ github.sha }}
        run: |
          set -e

          settings="[]"

          process_directory() {
            for file in "settings/*.txt; do
              if [ -f "$file" ]; then
                setting_id=$(basename "$file" .txt)
                raw_url="https://raw.githubusercontent.com/${REPO_URL}/${COMMIT_HASH}/${file}"
                checksum=$(sha256sum "$file" | cut -d ' ' -f 1)
                timestamp=$(git log -1 --format=%ai -- "$file" | cut -d ' ' -f 1,2 | tr ' ' 'T')Z
                contributors=$(git log -1 --format='%an <%ae>' -- "$file")

                settings=$(echo "$settings" | jq --arg name "$setting_id" \
                                                          --arg url "$raw_url" \
                                                          --arg checksum "$checksum" \
                                                          --arg timestamp "$timestamp" \
                                                          --arg contributors "$contributors" \
                                                          '. += [{
                                                            "name": $name,
                                                            "url": $url,
                                                            "checksum": $checksum,
                                                            "timestamp": $timestamp,
                                                            "contributors": $contributors
                                                          }]')
              fi
            done
          }

          echo "$settings" > settings.json
          
          echo "Uploading settings..."
          for file in settings/legacy/*.txt settings/nextgen/*.txt; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              setting_id=$(basename "$file" .txt)
              url="https://api.rinbounce.wtf/server/settings/${filename}"
              curl --fail -X POST \
                -H "Authorization: Bearer $AUTHORIZATION" \
                -H "Content-Type: application/json" \
                -d @"settings.json" \
                "$url" \
                && echo "Settings for $filename successfully uploaded to $url" \
                || (echo "Failed to upload settings for $filename" && exit 1)
            fi
          done

      - name: Upload JSON Files to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: settings
          path: 'settings.json'
